### ISSUE TITLE
Website bug

### ISSUE THREAD

**Issue by socketpair** [mapillary/mapillary_localization#41]
Cannot use top menu from iPad. On attached image, menu items are not usable (if I click, nothing happen. And menu just closed)
![image](https://cloud.githubusercontent.com/assets/1157412/10323010/ebdc8dda-6c99-11e5-838d-7e9f53f88346.png)

**Comment by knikel** [comment]
Thanks @socketpair I'm looking into that, this is being tracked in https://github.com/mapillary/mapillary_issues/issues/1443
