### ISSUE TITLE
Translation is not shown on the website!

### ISSUE THREAD

**Issue by velmyshanovnyi** [mapillary/mapillary_localization#43]
translation is not shown on the website!

http://www.mapillary.com/

for all languages!!!

**Comment by knikel** [comment]
Hi @velmyshanovnyi, thanks for your feedback! We're aware of the fact that translations are incomplete and not all languages are supported. We're in the process of rebuilding whole mapillary.com. We'll tackle a better and more scalable solution of for community driven translations when we roll out the new platform.
